### ISSUE TITLE
MIDDLEWARE_CLASSES is deprecated after Django 1.10

### ISSUE THREAD

**Issue by LihengGong** [fanout/django-liveresource#1]
There is no `MIDDLEWARE_CLASSES` in Django 2.0.7 code.

If I insert `'django_liveresource.LiveResourceMiddleware'` directly in `MIDDLEWARE`, Django will complain:

> System check identified no issues (0 silenced).
July 16, 2018 - 18:20:12
Django version 2.0.7, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x10c1d8598>
Traceback (most recent call last):
  File "/liveresource/django-liveresource/venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/liveresource/django-liveresource/venv/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 140, in inner_run
    handler = self.get_handler(*args, **options)
  File "/liveresource/django-liveresource/venv/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
    handler = super().get_handler(*args, **options)
  File "/liveresource/django-liveresource/venv/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 65, in get_handler
    return get_internal_wsgi_application()
  File "/liveresource/django-liveresource/venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 44, in get_internal_wsgi_application
    return import_string(app_path)
  File "/liveresource/django-liveresource/venv/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/liveresource/django-liveresource/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/liveresource/django-liveresource/mysite/mysite/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/liveresource/django-liveresource/venv/lib/python3.6/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    return WSGIHandler()
  File "/liveresource/django-liveresource/venv/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 140, in __init__
    self.load_middleware()
  File "/liveresource/django-liveresource/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 39, in load_middleware
    mw_instance = middleware(handler)
TypeError: object() takes no parameters

**Comment by LihengGong** [comment]
Kindly considering align the code with Django 2. Thank you

**Comment by jkarneges** [comment]
Hi, this project is incomplete, so porting won't be enough.

Hopefully someday we can do more development with LiveResource but for now it remains mostly an interesting idea.

**Comment by LihengGong** [comment]
Just curious: what this module is intended for?

Anyway, the `MIDDLEWARE_CLASSES` can be fixed by this:
https://stackoverflow.com/questions/42232606/django-exception-middleware-typeerror-object-takes-no-parameters

**Comment by jkarneges** [comment]
The module was intended to implement the [LiveResource protocol](https://github.com/liveresource/protocol/blob/master/liveresource-protocol.md), to provide easy realtime API development.

I believe all the server developer would need to do is add a `@live` decorator on any view functions that need to serve live data, and call `updated()` whenever the content of a view has changed. At least that was the goal, if this project were finished.

**Comment by LihengGong** [comment]
Very helpful. Thank you
